application: thinkfuse-postbin
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
- url: /stats
  script: main.py
- url: /tasks.*
  script: main.py
- url: /blacklist
  script: main.py
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /.*
  script: bin.py
